name: Build Release

on:
  workflow_dispatch:

jobs:

  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      PACKAGE_NAME: 'dev.foxscore.easy-login'
    steps:

    - name: Checkout
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

    - name: Get Version
      id: version
      uses: zoexx/github-action-json-file-properties@b9f36ce6ee6fe2680cd3c32b2c62e22eade7e590
      with: 
        file_path: "package.json"
        prop_path: "version"

    - name: Set Environment Variables
      run: |
        echo "zipFile=${{ env.PACKAGE_NAME }}-${{ steps.version.outputs.value }}".zip >> $GITHUB_ENV
        echo "unityPackage=${{ env.PACKAGE_NAME }}-${{ steps.version.outputs.value }}.unitypackage" >> $GITHUB_ENV
        echo "version=${{ steps.version.outputs.value }}" >> $GITHUB_ENV

    - name: Check if Version is Prerelease
      id: is_prerelease
      run: |
        echo "::set-output name=is_prerelease::$([[ "${{ env.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+-(.+)$ ]] && echo true || echo false)"

    - name: Create Package Zip
      run: zip -r "/tmp/${{ env.zipFile }}" .

    - name: Create UnityPackage
      uses: foxscore/make-unitypackage@cbd3def23d6c9910b56e726b193c2363e5ca6adc
      with:
        path: .
        saveTo: /tmp/${{ env.unityPackage }}
        prefix: Packages/dev.foxscore.${{ env.PACKAGE_NAME }}/

    - name: Create Tag
      id: tag_version
      uses: rickstaa/action-create-tag@88dbf7ff6fe2405f8e8f6c6fdfd78829bc631f83
      with:
        tag: "${{ env.version }}"

    - name: Make Release
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
      with:
        files: |
          /tmp/${{ env.zipFile }}
          /tmp/${{ env.unityPackage }}
          package.json
        tag_name: ${{ env.version }}
        prerelease: ${{ steps.is_prerelease.outputs.is_prerelease }}

    - name: Update Repository
      uses: convictional/trigger-workflow-and-wait@v1.6.5
      with:
        owner: 'foxscore'
        repo: 'www'
        github_token: ${{ secrets.PAT_WWW_WORKFLOW }}
        workflow_file_name: publish.yaml
